name: Auto Release on main Merge

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants write access to repository content

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Current Version Tag
        id: get_version
        run: |
          if git describe --tags $(git rev-list --tags --max-count=1) >/dev/null 2>&1; then
            latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          else
            latest_tag="v0.0.0"
          fi

          echo "Latest tag: $latest_tag"
          major=$(echo "$latest_tag" | cut -d. -f1 | cut -dv -f2)
          minor=$(echo "$latest_tag" | cut -d. -f2)
          minor=$((minor + 1))
          new_tag="v${major}.${minor}.0"
          echo "New tag: $new_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push New Tag
        run: |
          git tag "$new_tag"
          git push origin "$new_tag"

      - name: Authenticate with GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$new_tag" \
            --title "$new_tag" \
            --notes "Automated release for changes merged into main."
